### ISSUE TITLE
Python Scripts

### ISSUE THREAD

**Issue by jb-alvarado** [lucaskenda/handyscripts#1]
Hello,
first of all - thank you for your handy extension! 

I wanted to ask, if it is difficult do add also python script support to this extension? Python can have two formats ***.py** and ***.pyw**.

**Comment by lucaskenda** [comment]
Hi! I am doing a new version in the repo handyscripts2 and I'll keep Python support.
Every time you make a new version in Gnome Shell extensions it removes the folder and add the new. The default path is the folder "scripts" and as soon as I publish a new version it removes all custom scripts from everyone.
In the new version it will be mandatory to set a new folder so we can do changes.
